/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-dc4387b5f5a71cc1c35f02124338ae55f24e0954
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFieldUpdatedContextOptionsList : A list of custom field options for a context.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldUpdatedContextOptionsList {
    /// The updated custom field options.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::CustomFieldOptionUpdate>>,
}

impl CustomFieldUpdatedContextOptionsList {
    /// A list of custom field options for a context.
    pub fn new() -> CustomFieldUpdatedContextOptionsList {
        CustomFieldUpdatedContextOptionsList {
            options: None,
        }
    }
}

