/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-dc4387b5f5a71cc1c35f02124338ae55f24e0954
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JiraMultipleSelectField {
    #[serde(rename = "fieldId")]
    pub field_id: String,
    #[serde(rename = "options")]
    pub options: Vec<models::JiraSelectedOptionField>,
}

impl JiraMultipleSelectField {
    pub fn new(field_id: String, options: Vec<models::JiraSelectedOptionField>) -> JiraMultipleSelectField {
        JiraMultipleSelectField {
            field_id,
            options,
        }
    }
}

