/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-dc4387b5f5a71cc1c35f02124338ae55f24e0954
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationSchemeEventTypeId : The ID of an event that is being mapped to notifications.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationSchemeEventTypeId {
    /// The ID of the notification scheme event.
    #[serde(rename = "id")]
    pub id: String,
}

impl NotificationSchemeEventTypeId {
    /// The ID of an event that is being mapped to notifications.
    pub fn new(id: String) -> NotificationSchemeEventTypeId {
        NotificationSchemeEventTypeId {
            id,
        }
    }
}

