/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-dc4387b5f5a71cc1c35f02124338ae55f24e0954
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParsedJqlQueries : A list of parsed JQL queries.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParsedJqlQueries {
    /// A list of parsed JQL queries.
    #[serde(rename = "queries")]
    pub queries: Vec<models::ParsedJqlQuery>,
}

impl ParsedJqlQueries {
    /// A list of parsed JQL queries.
    pub fn new(queries: Vec<models::ParsedJqlQuery>) -> ParsedJqlQueries {
        ParsedJqlQueries {
            queries,
        }
    }
}

