/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-dc4387b5f5a71cc1c35f02124338ae55f24e0954
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScreenSchemeId : The ID of a screen scheme.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenSchemeId {
    /// The ID of the screen scheme.
    #[serde(rename = "id")]
    pub id: i64,
}

impl ScreenSchemeId {
    /// The ID of a screen scheme.
    pub fn new(id: i64) -> ScreenSchemeId {
        ScreenSchemeId {
            id,
        }
    }
}

